version: 2

jobs:
  build:
    docker:
      - image: golang:1.14
    working_directory: /rosetta-filecoin-lib
    steps:
      - checkout
      - run: go build
      - run: go test ./...

  checks:
    docker:
      - image: golang:1.14
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
      - run: golangci-lint --version
      - run: golangci-lint run -E gofmt -E gosec -E goconst -E gocritic
#      - run: golangci-lint run -E stylecheck -E gosec -E goconst -E godox -E gocritic

workflows:
  version: 2
  build_all:
    jobs:
      - checks
      - build
