version: 2

jobs:
  build:
    docker:
      - image: golang:1.17
    working_directory: /rosetta-filecoin-lib
    steps:
      - checkout
      - run: make test

  checks:
    docker:
      - image: golang:1.17
    steps:
      - checkout
      - run: make install_lint
      - run: make lint

workflows:
  version: 2
  build_all:
    jobs:
      - checks
      - build
