name: Build and check

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Test
        run: make test
        env:
          LOTUS_URL: ${{ secrets.LOTUS_URL }}
          LOTUS_JWT: ${{ secrets.LOTUS_JWT }}

  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
