name: Build and check

on:
  - push

jobs:
  build:
    runs-on: zondax-runners
    container:
      image: golang:1.23.7
      options: --tty
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'
      - name: Install dependencies
        run: apt update && apt install -yy build-essential
      - name: Build
        run: make build

  test:
    runs-on: zondax-runners
    container:
      image: golang:1.23.7
      options: --tty
    environment: CALIBRATION
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.7'
      - name: Install dependencies
        run: apt update && apt install -yy build-essential
      - name: Test
        run: make test
        env:
          LOTUS_URL: ${{ secrets.LOTUS_URL_CALIBNET }}
          AUTH_JWT: ${{ secrets.AUTH_JWT }}
