name: Build and check

on:
  - push

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20'
      - name: Test
        run: make test
        env:
          LOTUS_URL: ${{ secrets.LOTUS_URL_DEVNET }}
          AUTH_JWT: ${{ secrets.LOTUS_JWT_DEVNET }}

  checks:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.20'
